"use strict";
const $=id=>document.getElementById(id);
let csrf="",config=null,scanTimer=null,toastTimer=null,activeCameraId="";
let autostartState=false;
let configSave=Promise.resolve();
const deviceBusy={camera:new Set(),serial:new Set()};

function toast(message,error=false){const el=$("toast");el.textContent=message;el.className=error?"show error":"show";clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.className="",4200)}
async function api(path,options={}){const headers={"X-CSRF-Token":csrf,...options.headers};if(options.body)headers["Content-Type"]="application/json";const response=await fetch(path,{...options,headers});let data;try{data=await response.json()}catch{data={}}if(!response.ok)throw new Error(data.error?.message||`HTTP ${response.status}`);return data}
function escapeHtml(value){return String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function formatBytes(value){if(!Number.isFinite(value))return"--";const units=["B","KiB","MiB","GiB","TiB"];let i=0;while(value>=1024&&i<units.length-1){value/=1024;i++}return`${value.toFixed(i?1:0)} ${units[i]}`}
function stateClass(value){return["complete","running","ok","no_plate","bound"].includes(value)?"ok":["failed","attention","stopped","lost"].includes(value)?"bad":"warn"}
function setError(target,message=""){const element=typeof target==="string"?$(target):target;if(element)element.textContent=message}
function cloneConfig(){const value=JSON.parse(JSON.stringify(config));delete value.secret_status;return value}
function inputNumber(input,label,integer=false){const value=Number(input.value);if(input.value.trim()===""||!Number.isFinite(value)||(integer&&!Number.isInteger(value))||!input.checkValidity())throw new Error(`${label}无效`);return value}
function numberValue(id,label,integer=false){return inputNumber($(id),label,integer)}
function validateDeviceId(value,label){if(!/^[A-Za-z0-9_-]{1,40}$/.test(value))throw new Error(`${label}仅允许 1-40 位字母、数字、下划线或短横线`);return value}
function displayTrigger(item){const value=String(item.trigger??"");return item.mode==="text"?value.replace(/\\/g,"\\\\").replace(/\r/g,"\\r").replace(/\n/g,"\\n").replace(/\t/g,"\\t"):value}
function parseTextTrigger(value){return value.replace(/\\(\\|r|n|t)/g,(_match,key)=>({"\\":"\\","r":"\r","n":"\n","t":"\t"}[key]))}
function setDeviceBusy(type,id,busy){deviceBusy[type][busy?"add":"delete"](id);const attribute=type==="camera"?"data-camera-id":"data-serial-id";[...document.querySelectorAll(`[${attribute}]`)].find(item=>item.getAttribute(attribute)===id)?.querySelectorAll("button").forEach(item=>item.disabled=busy)}
function deviceError(type,id,fallback,message){const attribute=type==="camera"?"data-camera-id":"data-serial-id",editor=[...document.querySelectorAll(`[${attribute}]`)].find(item=>item.getAttribute(attribute)===id);setError(editor?.querySelector(".form-error")||fallback,message)}
function sameDevice(current,expected){return JSON.stringify(current)===expected}

function renderHttp(){$("config-version").value=config.version;$("http-host").value=config.http.host;$("http-port").value=config.http.port;setError("http-error")}
function renderRecording(){$("recording-pre-seconds").value=config.recording.pre_seconds;$("recording-post-seconds").value=config.recording.post_seconds;$("recording-segment-seconds").value=config.recording.segment_seconds;setError("recording-error")}
function renderPreviewConfig(){$("preview-width").value=config.preview.width;$("preview-fps").value=config.preview.fps;$("preview-idle-seconds").value=config.preview.idle_seconds;setError("preview-error")}
function renderOcr(){$("ocr-enabled").checked=config.ocr.enabled;$("ocr-fps").value=config.ocr.fps;$("ocr-confidence").value=config.ocr.confidence;$("ocr-cpu-threads").value=config.ocr.cpu_threads;setError("ocr-error")}
function renderUpload(){const upload=config.upload,state=config.secret_status||{};$("upload-delete-after-success").checked=upload.delete_after_success;$("upload-connect-timeout").value=upload.connect_timeout;$("upload-read-timeout").value=upload.read_timeout;$("upload-total-timeout").value=upload.total_timeout;$("upload-max-retries").value=upload.max_retries;for(const id of["text-url","video-url","api-token"])$(id).value="";for(const id of["clear-text-url","clear-video-url","clear-token"])$(id).checked=false;$("secret-state").textContent=`已配置：事件接口 ${state.text_url?"是":"否"}，视频接口 ${state.video_url?"是":"否"}，Token ${state.token?"是":"否"}`;setError("upload-error")}
function renderStorage(){$("storage-reserve-percent").value=config.storage.reserve_percent;$("storage-reserve-bytes").value=config.storage.reserve_bytes;$("storage-cache-keep-seconds").value=config.storage.cache_keep_seconds;setError("storage-error")}
function renderPreviews(){const cameras=(config?.cameras||[]).filter(item=>item.enabled!==false);$("camera-count").textContent=`${cameras.length} 路`;if(!cameras.some(item=>item.id===activeCameraId))activeCameraId=cameras[0]?.id||"";const active=cameras.find(item=>item.id===activeCameraId);$("previews").innerHTML=active?`<div class="preview-tabs">${cameras.map(item=>`<button class="${item.id===activeCameraId?"active":""}" data-camera="${escapeHtml(item.id)}">${escapeHtml(item.name||item.id)}</button>`).join("")}<button class="ghost" data-unbind="${escapeHtml(active.id)}">取消绑定</button></div><div class="preview"><img src="/api/preview/${encodeURIComponent(active.id)}" alt="${escapeHtml(active.name||active.id)}"><span>${escapeHtml(active.name||active.id)}</span></div>`:'<div class="empty">尚未添加摄像头</div>'}
function renderCameraSettings(){const cameras=config?.cameras||[];$("camera-settings").innerHTML=cameras.map(camera=>`<article class="device-editor" data-camera-id="${escapeHtml(camera.id)}"><div class="device-editor-title"><div><strong>${escapeHtml(camera.name||camera.id)}</strong><small>${escapeHtml(camera.id)}</small></div><label class="check-row"><input data-camera-field="enabled" type="checkbox" ${camera.enabled!==false?"checked":""}>启用</label></div><div class="form-grid"><label>摄像头 ID<input data-camera-field="id" value="${escapeHtml(camera.id)}" readonly></label><label>名称<input data-camera-field="name" value="${escapeHtml(camera.name||"")}" maxlength="80"></label><label>主码流 RTSP 地址<input data-camera-field="rtsp_url" value="${escapeHtml(camera.rtsp_url||"")}" required></label><label>预览 RTSP 地址（可选）<input data-camera-field="preview_url" value="${escapeHtml(camera.preview_url||"")}" placeholder="留空使用主码流"></label><label>实时转发目标（可选）<input data-camera-field="forward_url" value="${escapeHtml(camera.forward_url||"")}" placeholder="192.168.2.20:5000"></label></div><div class="actions"><button data-camera-save ${deviceBusy.camera.has(camera.id)?"disabled":""}>保存此摄像头</button><button data-camera-delete class="danger" ${deviceBusy.camera.has(camera.id)?"disabled":""}>删除摄像头</button></div><p class="form-error" aria-live="polite"></p></article>`).join("")||'<div class="empty">尚未绑定摄像头</div>';$("camera-add").disabled=cameras.length>=2}
function renderSerialSettings(){const serials=config?.serial_ports||[];$("serial-settings").innerHTML=serials.map(item=>`<article class="device-editor" data-serial-id="${escapeHtml(item.device_id)}"><div class="device-editor-title"><div><strong>${escapeHtml(item.device_id)}</strong><small>串口触发设备</small></div><label class="check-row"><input data-serial-field="enabled" type="checkbox" ${item.enabled!==false?"checked":""}>启用</label></div><div class="form-grid"><label>设备 ID<input data-serial-field="device_id" value="${escapeHtml(item.device_id)}" maxlength="40" pattern="[A-Za-z0-9_-]{1,40}" required></label><label>波特率<input data-serial-field="baudrate" type="number" min="300" max="4000000" step="1" value="${escapeHtml(item.baudrate)}" required></label><label>触发模式<select data-serial-field="mode"><option value="text" ${item.mode==="text"?"selected":""}>text</option><option value="hex" ${item.mode==="hex"?"selected":""}>hex</option></select></label><label>触发指令<textarea data-serial-field="trigger" rows="3" required>${escapeHtml(displayTrigger(item))}</textarea></label></div><p class="muted">text 模式可使用 \\r、\\n、\\t 表示控制字符。</p><div class="actions"><button data-serial-save ${deviceBusy.serial.has(item.device_id)?"disabled":""}>保存此串口</button><button data-serial-delete class="danger" ${deviceBusy.serial.has(item.device_id)?"disabled":""}>删除串口</button></div><p class="form-error" aria-live="polite"></p></article>`).join("")||'<div class="empty">尚未配置串口设备</div>';$("serial-add").disabled=serials.length>=16}

const configRenderers={http:renderHttp,recording:renderRecording,preview:renderPreviewConfig,ocr:renderOcr,upload:renderUpload,storage:renderStorage,cameras:renderCameraSettings,serials:renderSerialSettings};
function renderConfig(value,sections=null){config=value;for(const section of sections||Object.keys(configRenderers))configRenderers[section]();if(!sections||sections.some(section=>["recording","preview","cameras"].includes(section)))renderPreviews()}

function renderStatus(status){const free=status.disk?.free,total=status.disk?.total;$("disk").textContent=`可用 ${formatBytes(free)} / ${formatBytes(total)}`;$("summary").textContent=status.accepting_events?`运行中 · 队列 拼接 ${status.queues.stitch} / OCR ${status.queues.ocr} / 上传 ${status.queues.upload}`:"磁盘空间不足，已暂停新事件";$("serials").innerHTML=Object.entries(status.serials||{}).map(([id,item])=>`<div class="status-card"><strong>${escapeHtml(id)}</strong><span class="${stateClass(item.state)}">${item.state==="bound"?"已绑定":item.state==="lost"?"连接已断开":"正在扫描"}</span><br><span>${item.port?`当前端口 ${escapeHtml(item.port)}`:`已检查 ${item.checked||0} 个端口`}</span>${item.error?`<br><span class="muted">${escapeHtml(item.error)}</span>`:""}</div>`).join("")||'<div class="empty">尚未配置串口设备</div>';$("recorders").innerHTML=Object.entries(status.recorders||{}).map(([id,item])=>`<div class="status-card"><strong>${escapeHtml(id)}</strong><span class="${stateClass(item.state)}">${escapeHtml(item.state)}</span><br><span>重连 ${item.restarts||0} 次</span>${item.error?`<br><span class="bad" title="${escapeHtml(item.error)}">${escapeHtml(item.error.slice(0,100))}</span>`:""}</div>`).join("")||'<div class="empty">没有运行中的录像器</div>';$("forwarders").innerHTML=Object.entries(status.forwarders||{}).map(([id,item])=>`<div class="status-card"><strong>${escapeHtml(id)}</strong><span class="${stateClass(item.state)}">${escapeHtml(item.state)}</span><br><span>${escapeHtml(item.target)} · 重连 ${item.restarts||0} 次</span>${item.error?`<br><span class="bad" title="${escapeHtml(item.error)}">${escapeHtml(item.error.slice(0,100))}</span>`:""}</div>`).join("")||'<div class="empty">尚未配置实时转发</div>';$("errors").innerHTML=(status.errors||[]).slice().reverse().map(item=>`<div>${escapeHtml(item.time)} · ${escapeHtml(item.message)}</div>`).join("")}
function renderEvents(items){$("events").innerHTML=items.map(item=>{const retry=item.text_upload.status!=="complete"||item.video_upload.status!=="complete";return`<tr><td>${new Date(item.trigger_time*1000).toLocaleString()}<br><small>${escapeHtml(item.event_id)}</small></td><td>${escapeHtml(item.camera_id)}</td><td class="${stateClass(item.recording.status)}" title="${escapeHtml(item.recording.error||item.coverage.reason||"")}">${escapeHtml(item.recording.status)}</td><td class="${stateClass(item.ocr.status)}" title="${escapeHtml(item.ocr.error||"")}">${escapeHtml(item.ocr.status)} (${item.ocr.failed_frames||0}/${item.ocr.frames||0} 失败)</td><td>${(item.ocr.plates||[]).map(plate=>`${escapeHtml(plate.text)} ${(plate.confidence*100).toFixed(1)}%`).join("<br>")||"—"}</td><td class="${stateClass(item.text_upload.status)}" title="${escapeHtml(item.text_upload.error||"")}">${escapeHtml(item.text_upload.status)}</td><td class="${stateClass(item.video_upload.status)}" title="${escapeHtml(item.video_upload.error||"")}">${escapeHtml(item.video_upload.status)}</td><td>${retry?`<button data-retry="${escapeHtml(item.event_id)}|${escapeHtml(item.camera_id)}">重试</button>`:""}</td></tr>`}).join("")||'<tr><td colspan="8" class="empty">暂无事件</td></tr>'}
function deviceName(item){return[item.manufacturer,item.model].filter(Boolean).join(" ")||`摄像头 ${item.ip}`}
function bestStream(item){return(item.streams||[]).filter(stream=>stream.validated).sort((a,b)=>(b.width||0)*(b.height||0)-(a.width||0)*(a.height||0))[0]}

async function refresh(){try{const[status,events]=await Promise.all([api("/api/status"),api("/api/events")]);renderStatus(status);renderEvents(events)}catch(error){toast(error.message,true)}}
async function refreshLoop(){await refresh();setTimeout(refreshLoop,2000)}
function serializeConfigSave(action){const pending=configSave.then(action,action);configSave=pending.catch(()=>{});return pending}
async function persistConfig(value,button,section,message,extra={}){delete value.secret_status;button.disabled=true;try{const saved=await api("/api/config",{method:"PUT",body:JSON.stringify({config:value,...extra})});const restart=Boolean(saved.restart_required);delete saved.restart_required;renderConfig(saved,[section]);toast(restart?`${message}；监听地址将在重启后生效`:message);await refresh();return saved}finally{button.disabled=false}}
async function persistConfigChange(button,section,message,build){return serializeConfigSave(async()=>{const value=cloneConfig(),extra=build(value)||{};return persistConfig(value,button,section,message,extra)})}
async function saveGroup(buttonId,errorId,section,message,build){const button=$(buttonId);setError(errorId);try{await persistConfigChange(button,section,message,build)}catch(error){setError(errorId,error.message);toast(error.message,true)}}

async function bootstrap(){try{const data=await api("/api/bootstrap");csrf=data.csrf_token;renderConfig(data.config);renderStatus(data.status);autostartState=(await api("/api/autostart")).enabled;$("autostart").textContent=autostartState?"取消开机自启":"设置开机自启";await refresh();setTimeout(refreshLoop,2000)}catch(error){toast(error.message,true)}}

$("refresh").onclick=refresh;
$("save-http").onclick=()=>saveGroup("save-http","http-error","http","基础服务配置已保存",value=>{value.http.host=$("http-host").value;value.http.port=numberValue("http-port","网页监听端口",true)});
$("save-recording").onclick=()=>saveGroup("save-recording","recording-error","recording","录像配置已保存并应用",value=>{value.recording.pre_seconds=numberValue("recording-pre-seconds","触发前录像时长",true);value.recording.post_seconds=numberValue("recording-post-seconds","触发后录像时长",true);value.recording.segment_seconds=numberValue("recording-segment-seconds","录像切片时长",true)});
$("save-preview").onclick=()=>saveGroup("save-preview","preview-error","preview","预览配置已保存并应用",value=>{value.preview.width=numberValue("preview-width","预览宽度",true);value.preview.fps=numberValue("preview-fps","预览帧率",true);value.preview.idle_seconds=numberValue("preview-idle-seconds","预览停止时间",true)});
$("save-ocr").onclick=()=>saveGroup("save-ocr","ocr-error","ocr","OCR 配置已保存并应用",value=>{value.ocr.enabled=$("ocr-enabled").checked;value.ocr.fps=numberValue("ocr-fps","OCR 抽样帧率",true);value.ocr.confidence=numberValue("ocr-confidence","OCR 最低置信度");value.ocr.cpu_threads=numberValue("ocr-cpu-threads","OCR CPU 线程数",true)});
$("save-upload").onclick=()=>saveGroup("save-upload","upload-error","upload","上传配置已保存并应用",value=>{value.upload.delete_after_success=$("upload-delete-after-success").checked;value.upload.connect_timeout=numberValue("upload-connect-timeout","连接超时");value.upload.read_timeout=numberValue("upload-read-timeout","读取超时");value.upload.total_timeout=numberValue("upload-total-timeout","总超时");value.upload.max_retries=numberValue("upload-max-retries","最大重试次数",true);return{secrets:{text_url:$("text-url").value.trim(),video_url:$("video-url").value.trim(),token:$("api-token").value},clear_secrets:[["clear-text-url","text_url"],["clear-video-url","video_url"],["clear-token","token"]].filter(item=>$(item[0]).checked).map(item=>item[1])}});
$("save-storage").onclick=()=>saveGroup("save-storage","storage-error","storage","存储配置已保存并应用",value=>{value.storage.reserve_percent=numberValue("storage-reserve-percent","磁盘保留比例");value.storage.reserve_bytes=numberValue("storage-reserve-bytes","最少保留字节数",true);value.storage.cache_keep_seconds=numberValue("storage-cache-keep-seconds","缓存保留时间",true)});

async function removeCamera(cameraId,button,errorTarget=null){const camera=config.cameras.find(item=>item.id===cameraId),name=camera?.name||cameraId,expected=JSON.stringify(camera);if(!camera)return toast("摄像头配置已变化，请刷新页面",true);if(!confirm(`确定删除摄像头“${name}”？历史事件和录像不会删除。`))return;setError(errorTarget);setDeviceBusy("camera",cameraId,true);button.closest("[data-camera-id]")?.querySelectorAll("button").forEach(item=>item.disabled=true);try{await serializeConfigSave(async()=>{const current=config.cameras.find(item=>item.id===cameraId);if(!current)throw new Error(`摄像头 ${cameraId} 已删除`);if(!sameDevice(current,expected))throw new Error(`摄像头 ${cameraId} 配置已变化，请重试`);const saved=await api(`/api/cameras/${encodeURIComponent(cameraId)}`,{method:"DELETE"});renderConfig(saved,["cameras"]);toast(`摄像头 ${name} 已删除`);await refresh()})}catch(error){deviceError("camera",cameraId,errorTarget,error.message);toast(error.message,true)}finally{setDeviceBusy("camera",cameraId,false);button.disabled=false}}
$("previews").onclick=async event=>{const unbind=event.target.closest("[data-unbind]");if(unbind){await removeCamera(unbind.dataset.unbind,unbind);return}const button=event.target.closest("[data-camera]");if(!button||button.dataset.camera===activeCameraId)return;activeCameraId=button.dataset.camera;renderPreviews()};
$("camera-settings").onclick=async event=>{const button=event.target.closest("button"),editor=button?.closest("[data-camera-id]");if(!button||!editor)return;const cameraId=editor.dataset.cameraId,camera=config.cameras.find(item=>item.id===cameraId),errorTarget=editor.querySelector(".form-error");if(!camera)return toast("摄像头配置已变化，请刷新页面",true);if(button.matches("[data-camera-delete]")){await removeCamera(cameraId,button,errorTarget);return}if(!button.matches("[data-camera-save]"))return;const expected=JSON.stringify(camera),fields={name:editor.querySelector('[data-camera-field="name"]').value.trim(),enabled:editor.querySelector('[data-camera-field="enabled"]').checked,rtsp_url:editor.querySelector('[data-camera-field="rtsp_url"]').value.trim(),preview_url:editor.querySelector('[data-camera-field="preview_url"]').value.trim(),forward_url:editor.querySelector('[data-camera-field="forward_url"]').value.trim()};setError(errorTarget);setDeviceBusy("camera",cameraId,true);editor.querySelectorAll("button").forEach(item=>item.disabled=true);try{await persistConfigChange(button,"cameras",`摄像头 ${cameraId} 配置已保存`,value=>{const updated=value.cameras.find(item=>item.id===cameraId);if(!updated)throw new Error(`摄像头 ${cameraId} 已删除`);if(!sameDevice(updated,expected))throw new Error(`摄像头 ${cameraId} 配置已变化，请重试`);Object.assign(updated,fields);if(!updated.rtsp_url)throw new Error("主码流 RTSP 地址不能为空")})}catch(error){deviceError("camera",cameraId,errorTarget,error.message);toast(error.message,true)}finally{setDeviceBusy("camera",cameraId,false)}};

$("camera-add").onclick=async()=>{const button=$("camera-add");setError("camera-add-error");try{button.disabled=true;await serializeConfigSave(async()=>{if(config.cameras.length>=2)throw new Error("最多只能配置 2 路摄像头");const id=$("camera-id").value.trim();if(id)validateDeviceId(id,"摄像头 ID");const main=$("camera-main").value.trim();if(!main)throw new Error("主码流 RTSP 地址不能为空");const camera=await api("/api/cameras",{method:"POST",body:JSON.stringify({id,name:$("camera-name").value.trim(),rtsp_url:main,preview_url:$("camera-preview").value.trim(),forward_url:$("camera-forward").value.trim()})});for(const field of["camera-id","camera-name","camera-main","camera-preview","camera-forward"])$(field).value="";renderConfig(await api("/api/config"),["cameras"]);toast(`摄像头 ${camera.id} 已添加`);await refresh()})}catch(error){setError("camera-add-error",error.message);toast(error.message,true)}finally{button.disabled=config?.cameras?.length>=2}};

$("serial-settings").onclick=async event=>{const button=event.target.closest("button"),editor=button?.closest("[data-serial-id]");if(!button||!editor)return;const deviceId=editor.dataset.serialId,item=config.serial_ports.find(value=>value.device_id===deviceId),errorTarget=editor.querySelector(".form-error");if(!item)return toast("串口配置已变化，请刷新页面",true);const expected=JSON.stringify(item);if(button.matches("[data-serial-delete]")){if(!confirm(`确定删除串口设备“${deviceId}”？`))return;setError(errorTarget);setDeviceBusy("serial",deviceId,true);try{await persistConfigChange(button,"serials",`串口设备 ${deviceId} 已删除`,value=>{const index=value.serial_ports.findIndex(current=>current.device_id===deviceId);if(index<0)throw new Error(`串口设备 ${deviceId} 已删除`);if(!sameDevice(value.serial_ports[index],expected))throw new Error(`串口设备 ${deviceId} 配置已变化，请重试`);value.serial_ports.splice(index,1)})}catch(error){deviceError("serial",deviceId,errorTarget,error.message);toast(error.message,true)}finally{setDeviceBusy("serial",deviceId,false)}return}if(!button.matches("[data-serial-save]"))return;setError(errorTarget);setDeviceBusy("serial",deviceId,true);try{const mode=editor.querySelector('[data-serial-field="mode"]').value,trigger=editor.querySelector('[data-serial-field="trigger"]').value,fields={device_id:editor.querySelector('[data-serial-field="device_id"]').value.trim(),baudrate:inputNumber(editor.querySelector('[data-serial-field="baudrate"]'),"串口波特率",true),mode,trigger:mode==="text"?parseTextTrigger(trigger):trigger,enabled:editor.querySelector('[data-serial-field="enabled"]').checked};await persistConfigChange(button,"serials",`串口设备 ${deviceId} 已保存`,value=>{const updated=value.serial_ports.find(current=>current.device_id===deviceId);if(!updated)throw new Error(`串口设备 ${deviceId} 已删除`);if(!sameDevice(updated,expected))throw new Error(`串口设备 ${deviceId} 配置已变化，请重试`);fields.device_id=validateDeviceId(fields.device_id,"串口设备 ID");if(!fields.trigger)throw new Error("触发指令不能为空");Object.assign(updated,fields)})}catch(error){deviceError("serial",deviceId,errorTarget,error.message);toast(error.message,true)}finally{setDeviceBusy("serial",deviceId,false)}};
$("serial-add").onclick=async()=>{const button=$("serial-add");setError("serial-add-error");try{await persistConfigChange(button,"serials","串口设备已添加",value=>{if(value.serial_ports.length>=16)throw new Error("最多只能配置 16 个串口设备");const mode=$("serial-new-mode").value,trigger=$("serial-new-trigger").value,item={device_id:validateDeviceId($("serial-new-id").value.trim(),"串口设备 ID"),baudrate:numberValue("serial-new-baudrate","串口波特率",true),mode,trigger:mode==="text"?parseTextTrigger(trigger):trigger,enabled:$("serial-new-enabled").checked};if(!item.trigger)throw new Error("触发指令不能为空");value.serial_ports.push(item)});$("serial-new-id").value="";$("serial-new-trigger").value=""}catch(error){setError("serial-add-error",error.message);toast(error.message,true)}};

$("scan-start").onclick=async()=>{try{await api("/api/scan",{method:"POST",body:JSON.stringify({subnet:$("subnet").value,port:$("onvif-port").value,username:$("onvif-user").value,password:$("onvif-pass").value})});$("onvif-pass").value="";toast("扫描已开始");pollScan()}catch(error){toast(error.message,true)}};
$("scan-cancel").onclick=async()=>{try{await api("/api/scan",{method:"DELETE"});toast("已请求取消扫描")}catch(error){toast(error.message,true)}};
async function pollScan(){clearTimeout(scanTimer);try{const data=await api("/api/scan");$("scan-progress").textContent=`${data.status} · ${data.completed}/${data.total} · 发现 ${data.found.length} · 失败 ${Object.keys(data.failures).length}`;$("scan-results").innerHTML=data.found.map((item,index)=>{const stream=bestStream(item),detail=stream?`主码流 ${stream.width||"?"}×${stream.height||"?"} · ${(stream.codec||"").toUpperCase()} · 已验证`:"没有验证通过的 RTSP 流";return`<div class="list-item"><div><strong>${escapeHtml(deviceName(item))}</strong><small>${escapeHtml(item.ip)} · ${escapeHtml(detail)}</small></div><button data-discovered="${index}" ${stream&&config.cameras.length<2?"":"disabled"}>添加此摄像头</button></div>`}).join("");$("scan-results").dataset.items=JSON.stringify(data.found);if(data.status==="running")scanTimer=setTimeout(pollScan,1000)}catch(error){toast(error.message,true)}}
$("scan-results").onclick=async event=>{const button=event.target.closest("[data-discovered]");if(!button)return;try{button.disabled=true;const items=JSON.parse($("scan-results").dataset.items||"[]"),item=items[Number(button.dataset.discovered)];if(!bestStream(item))throw new Error("设备没有验证通过的 RTSP 流");await serializeConfigSave(async()=>{if(config.cameras.length>=2)throw new Error("最多只能配置 2 路摄像头");const id=`cam_${item.ip.replaceAll(".","_")}`;await api("/api/cameras",{method:"POST",body:JSON.stringify({id,name:deviceName(item),scan_ip:item.ip,forward_url:$("scan-forward").value})});renderConfig(await api("/api/config"),["cameras"]);toast(`已添加 ${deviceName(item)}`);await refresh()})}catch(error){button.disabled=false;toast(error.message,true)}};
$("events").onclick=async event=>{const button=event.target.closest("[data-retry]");if(!button)return;const[eventId,cameraId]=button.dataset.retry.split("|");try{await api(`/api/events/${encodeURIComponent(eventId)}/${encodeURIComponent(cameraId)}/retry`,{method:"POST",body:"{}"});toast("任务已重新入队")}catch(error){toast(error.message,true)}};
$("autostart").onclick=async()=>{try{autostartState=!autostartState;await api("/api/autostart",{method:"PUT",body:JSON.stringify({enabled:autostartState})});$("autostart").textContent=autostartState?"取消开机自启":"设置开机自启";toast(autostartState?"已设置当前用户登录后自动运行":"已取消开机自启")}catch(error){autostartState=!autostartState;toast(error.message,true)}};
bootstrap();
