"use strict";
const $=id=>document.getElementById(id);
let csrf="",config=null,scanTimer=null,toastTimer=null,activeCameraId="";
let autostartState=false;
function toast(message,error=false){const el=$("toast");el.textContent=message;el.className=error?"show error":"show";clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.className="",4200)}
async function api(path,options={}){const headers={"X-CSRF-Token":csrf,...options.headers};if(options.body)headers["Content-Type"]="application/json";const response=await fetch(path,{...options,headers});let data;try{data=await response.json()}catch{data={}}if(!response.ok)throw new Error(data.error?.message||`HTTP ${response.status}`);return data}
function formatBytes(value){if(!Number.isFinite(value))return"--";const units=["B","KiB","MiB","GiB","TiB"];let i=0;while(value>=1024&&i<units.length-1){value/=1024;i++}return`${value.toFixed(i?1:0)} ${units[i]}`}
function stateClass(value){return["complete","running","ok","no_plate","bound"].includes(value)?"ok":["failed","attention","stopped","lost"].includes(value)?"bad":"warn"}
function renderConfig(value){config=value;$("config").value=JSON.stringify(value,null,2);const state=value.secret_status||{};$("secret-state").textContent=`已配置：事件接口 ${state.text_url?"是":"否"}，视频接口 ${state.video_url?"是":"否"}，Token ${state.token?"是":"否"}`;renderPreviews();renderForwardSettings()}
function renderPreviews(){const cameras=(config?.cameras||[]).filter(x=>x.enabled!==false);$("camera-count").textContent=`${cameras.length} 路`;if(!cameras.some(c=>c.id===activeCameraId))activeCameraId=cameras[0]?.id||"";const active=cameras.find(c=>c.id===activeCameraId);$("previews").innerHTML=active?`<div class="preview-tabs">${cameras.map(c=>`<button class="${c.id===activeCameraId?"active":""}" data-camera="${c.id}">${escapeHtml(c.name||c.id)}</button>`).join("")}<button class="ghost" data-unbind="${active.id}">取消绑定</button></div><div class="preview"><img src="/api/preview/${encodeURIComponent(active.id)}" alt="${escapeHtml(active.name||active.id)}"><span>${escapeHtml(active.name||active.id)}</span></div>`:'<div class="empty">尚未添加摄像头</div>'}
function renderForwardSettings(){const cameras=config?.cameras||[];$("forward-settings").innerHTML=cameras.map(camera=>`<div class="list-item"><div><strong>${escapeHtml(camera.name||camera.id)}</strong><small>${escapeHtml(camera.id)} · 支持 IP、IP:端口或 udp://IP:端口</small></div><div class="actions"><input value="${escapeHtml(camera.forward_url||"")}" placeholder="192.168.2.20:5000"><button data-forward-save="${escapeHtml(camera.id)}">保存目标</button></div></div>`).join("")||'<div class="empty">尚未绑定摄像头</div>'}
function renderStatus(status){const free=status.disk?.free,total=status.disk?.total;$("disk").textContent=`可用 ${formatBytes(free)} / ${formatBytes(total)}`;$("summary").textContent=status.accepting_events?`运行中 · 队列 拼接 ${status.queues.stitch} / OCR ${status.queues.ocr} / 上传 ${status.queues.upload}`:"磁盘空间不足，已暂停新事件";$("serials").innerHTML=Object.entries(status.serials||{}).map(([id,item])=>`<div class="status-card"><strong>${escapeHtml(id)}</strong><span class="${stateClass(item.state)}">${item.state==="bound"?"已绑定":item.state==="lost"?"连接已断开":"正在扫描"}</span><br><span>${item.port?`当前端口 ${escapeHtml(item.port)}`:`已检查 ${item.checked||0} 个端口`}</span>${item.error?`<br><span class="muted">${escapeHtml(item.error)}</span>`:""}</div>`).join("")||'<div class="empty">尚未配置串口设备</div>';$("recorders").innerHTML=Object.entries(status.recorders||{}).map(([id,item])=>`<div class="status-card"><strong>${escapeHtml(id)}</strong><span class="${stateClass(item.state)}">${escapeHtml(item.state)}</span><br><span>重连 ${item.restarts||0} 次</span>${item.error?`<br><span class="bad" title="${escapeHtml(item.error)}">${escapeHtml(item.error.slice(0,100))}</span>`:""}</div>`).join("")||'<div class="empty">没有运行中的录像器</div>';$("forwarders").innerHTML=Object.entries(status.forwarders||{}).map(([id,item])=>`<div class="status-card"><strong>${escapeHtml(id)}</strong><span class="${stateClass(item.state)}">${escapeHtml(item.state)}</span><br><span>${escapeHtml(item.target)} · 重连 ${item.restarts||0} 次</span>${item.error?`<br><span class="bad" title="${escapeHtml(item.error)}">${escapeHtml(item.error.slice(0,100))}</span>`:""}</div>`).join("")||'<div class="empty">尚未配置实时转发</div>';$("errors").innerHTML=(status.errors||[]).slice().reverse().map(x=>`<div>${escapeHtml(x.time)} · ${escapeHtml(x.message)}</div>`).join("")}
function renderEvents(items){$("events").innerHTML=items.map(x=>{const retry=x.text_upload.status!=="complete"||x.video_upload.status!=="complete";return`<tr><td>${new Date(x.trigger_time*1000).toLocaleString()}<br><small>${escapeHtml(x.event_id)}</small></td><td>${escapeHtml(x.camera_id)}</td><td class="${stateClass(x.recording.status)}" title="${escapeHtml(x.recording.error||x.coverage.reason||"")}">${escapeHtml(x.recording.status)}</td><td class="${stateClass(x.ocr.status)}" title="${escapeHtml(x.ocr.error||"")}">${escapeHtml(x.ocr.status)} (${x.ocr.failed_frames||0}/${x.ocr.frames||0} 失败)</td><td>${(x.ocr.plates||[]).map(p=>`${escapeHtml(p.text)} ${(p.confidence*100).toFixed(1)}%`).join("<br>")||"—"}</td><td class="${stateClass(x.text_upload.status)}" title="${escapeHtml(x.text_upload.error||"")}">${escapeHtml(x.text_upload.status)}</td><td class="${stateClass(x.video_upload.status)}" title="${escapeHtml(x.video_upload.error||"")}">${escapeHtml(x.video_upload.status)}</td><td>${retry?`<button data-retry="${escapeHtml(x.event_id)}|${escapeHtml(x.camera_id)}">重试</button>`:""}</td></tr>`}).join("")||'<tr><td colspan="8" class="empty">暂无事件</td></tr>'}
function escapeHtml(value){return String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function deviceName(item){return[item.manufacturer,item.model].filter(Boolean).join(" ")||`摄像头 ${item.ip}`}
function bestStream(item){return(item.streams||[]).filter(x=>x.validated).sort((a,b)=>(b.width||0)*(b.height||0)-(a.width||0)*(a.height||0))[0]}
async function refresh(){try{const [status,events]=await Promise.all([api("/api/status"),api("/api/events")]);renderStatus(status);renderEvents(events)}catch(error){toast(error.message,true)}}
async function refreshLoop(){await refresh();setTimeout(refreshLoop,2000)}
async function bootstrap(){try{const data=await api("/api/bootstrap");csrf=data.csrf_token;renderConfig(data.config);renderStatus(data.status);autostartState=(await api("/api/autostart")).enabled;$("autostart").textContent=autostartState?"取消开机自启":"设置开机自启";await refresh();setTimeout(refreshLoop,2000)}catch(error){toast(error.message,true)}}
$("refresh").onclick=refresh;
$("previews").onclick=async event=>{const unbind=event.target.closest("[data-unbind]");if(unbind){const id=unbind.dataset.unbind,name=config.cameras.find(x=>x.id===id)?.name||id;if(!confirm(`确定取消绑定摄像头“${name}”？历史事件和录像不会删除。`))return;try{unbind.disabled=true;renderConfig(await api(`/api/cameras/${encodeURIComponent(id)}`,{method:"DELETE"}));toast(`摄像头 ${name} 已取消绑定`);await refresh()}catch(error){unbind.disabled=false;toast(error.message,true)}return}const button=event.target.closest("[data-camera]");if(!button||button.dataset.camera===activeCameraId)return;activeCameraId=button.dataset.camera;renderPreviews()};
$("forward-settings").onclick=async event=>{const button=event.target.closest("[data-forward-save]");if(!button)return;const value=JSON.parse(JSON.stringify(config)),camera=value.cameras.find(x=>x.id===button.dataset.forwardSave),target=button.closest(".list-item").querySelector("input").value.trim();delete value.secret_status;if(!camera)return toast("摄像头配置已变化，请刷新页面",true);camera.forward_url=target;try{button.disabled=true;const saved=await api("/api/config",{method:"PUT",body:JSON.stringify({config:value})});delete saved.restart_required;renderConfig(saved);toast(target?"实时转发目标已保存":"实时转发已停止");await refresh()}catch(error){button.disabled=false;toast(error.message,true)}};
$("save-config").onclick=async()=>{try{const value=JSON.parse($("config").value);delete value.secret_status;const secrets={text_url:$("text-url").value,video_url:$("video-url").value,token:$("api-token").value};const clear_secrets=[["clear-text-url","text_url"],["clear-video-url","video_url"],["clear-token","token"]].filter(x=>$(x[0]).checked).map(x=>x[1]);const saved=await api("/api/config",{method:"PUT",body:JSON.stringify({config:value,secrets,clear_secrets})});for(const id of ["text-url","video-url","api-token"])$(id).value="";for(const id of ["clear-text-url","clear-video-url","clear-token"])$(id).checked=false;const restart=saved.restart_required;delete saved.restart_required;renderConfig(saved);toast(restart?"配置已保存；HTTP 地址将在重启后生效":"配置已验证、保存并应用")}catch(error){toast(error.message,true)}};
$("camera-add").onclick=async()=>{try{const camera=await api("/api/cameras",{method:"POST",body:JSON.stringify({name:$("camera-name").value,rtsp_url:$("camera-main").value,forward_url:$("camera-forward").value})});$("camera-main").value="";toast(`摄像头 ${camera.id} 已添加`);renderConfig(await api("/api/config"))}catch(error){toast(error.message,true)}};
$("scan-start").onclick=async()=>{try{await api("/api/scan",{method:"POST",body:JSON.stringify({subnet:$("subnet").value,port:$("onvif-port").value,username:$("onvif-user").value,password:$("onvif-pass").value})});$("onvif-pass").value="";toast("扫描已开始");pollScan()}catch(error){toast(error.message,true)}};
$("scan-cancel").onclick=async()=>{try{await api("/api/scan",{method:"DELETE"});toast("已请求取消扫描")}catch(error){toast(error.message,true)}};
async function pollScan(){clearTimeout(scanTimer);try{const data=await api("/api/scan");$("scan-progress").textContent=`${data.status} · ${data.completed}/${data.total} · 发现 ${data.found.length} · 失败 ${Object.keys(data.failures).length}`;$("scan-results").innerHTML=data.found.map((item,index)=>{const stream=bestStream(item),detail=stream?`主码流 ${stream.width||"?"}×${stream.height||"?"} · ${(stream.codec||"").toUpperCase()} · 已验证`:`没有验证通过的 RTSP 流`;return`<div class="list-item"><div><strong>${escapeHtml(deviceName(item))}</strong><small>${escapeHtml(item.ip)} · ${escapeHtml(detail)}</small></div><button data-discovered="${index}" ${stream?"":"disabled"}>添加此摄像头</button></div>`}).join("");$("scan-results").dataset.items=JSON.stringify(data.found);if(data.status==="running")scanTimer=setTimeout(pollScan,1000)}catch(error){toast(error.message,true)}}
$("scan-results").onclick=async event=>{const button=event.target.closest("[data-discovered]");if(!button)return;try{const items=JSON.parse($("scan-results").dataset.items||"[]"),item=items[Number(button.dataset.discovered)];if(!bestStream(item))throw new Error("设备没有验证通过的 RTSP 流");const id=`cam_${item.ip.replaceAll(".","_")}`;await api("/api/cameras",{method:"POST",body:JSON.stringify({id,name:deviceName(item),scan_ip:item.ip,forward_url:$("scan-forward").value})});renderConfig(await api("/api/config"));toast(`已添加 ${deviceName(item)}`)}catch(error){toast(error.message,true)}};
$("events").onclick=async event=>{const button=event.target.closest("[data-retry]");if(!button)return;const[eventId,cameraId]=button.dataset.retry.split("|");try{await api(`/api/events/${encodeURIComponent(eventId)}/${encodeURIComponent(cameraId)}/retry`,{method:"POST",body:"{}"});toast("任务已重新入队")}catch(error){toast(error.message,true)}};
$("autostart").onclick=async()=>{try{autostartState=!autostartState;await api("/api/autostart",{method:"PUT",body:JSON.stringify({enabled:autostartState})});$("autostart").textContent=autostartState?"取消开机自启":"设置开机自启";toast(autostartState?"已设置当前用户登录后自动运行":"已取消开机自启")}catch(error){autostartState=!autostartState;toast(error.message,true)}};
bootstrap();
