"use strict";
const $=id=>document.getElementById(id);
let csrf="",config=null,scanTimer=null,toastTimer=null,activeCameraId="";
let autostartState=false;
let configSave=Promise.resolve();
const deviceBusy=new Set();

function toast(message,error=false){const el=$("toast");el.textContent=message;el.className=error?"show error":"show";clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.className="",4200)}
async function api(path,options={}){const headers={"X-CSRF-Token":csrf,...options.headers};if(options.body)headers["Content-Type"]="application/json";const response=await fetch(path,{...options,headers});let data;try{data=await response.json()}catch{data={}}if(!response.ok){const error=new Error(data.error?.message||`HTTP ${response.status}`);error.code=data.error?.code||"";if(error.code==="BROWSER_BUSY")blockBrowser(error.message);throw error}return data}
function blockBrowser(message){clearTimeout(toastTimer);document.querySelectorAll("button,input,select").forEach(item=>item.disabled=true);const el=$("toast");el.textContent=message;el.className="show error"}
function escapeHtml(value){return String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function formatBytes(value){if(!Number.isFinite(value))return"--";const units=["B","KiB","MiB","GiB","TiB"];let i=0;while(value>=1024&&i<units.length-1){value/=1024;i++}return`${value.toFixed(i?1:0)} ${units[i]}`}
function stateClass(value){return["complete","running","ok","no_plate","bound"].includes(value)?"ok":["failed","attention","stopped","lost"].includes(value)?"bad":"warn"}
function setError(target,message=""){const element=typeof target==="string"?$(target):target;if(element)element.textContent=message}
function cloneConfig(){const value=JSON.parse(JSON.stringify(config));delete value.secret_status;return value}
function inputNumber(input,label,integer=false){const value=Number(input.value);if(input.value.trim()===""||!Number.isFinite(value)||(integer&&!Number.isInteger(value))||!input.checkValidity())throw new Error(`${label}无效`);return value}
function numberValue(id,label,integer=false){return inputNumber($(id),label,integer)}
function validateDeviceId(value,label){if(!/^[A-Za-z0-9_-]{1,40}$/.test(value))throw new Error(`${label}仅允许 1-40 位字母、数字、下划线或短横线`);return value}
function setDeviceBusy(id,busy){deviceBusy[busy?"add":"delete"](id);[...document.querySelectorAll("[data-camera-id]")].find(item=>item.dataset.cameraId===id)?.querySelectorAll("button").forEach(item=>item.disabled=busy)}
function deviceError(id,fallback,message){const editor=[...document.querySelectorAll("[data-camera-id]")].find(item=>item.dataset.cameraId===id);setError(editor?.querySelector(".form-error")||fallback,message)}
function sameDevice(current,expected){return JSON.stringify(current)===expected}

function renderRecording(){$("recording-pre-seconds").value=config.recording.pre_seconds;$("recording-post-seconds").value=config.recording.post_seconds;setError("recording-error")}
function renderOcr(){$("ocr-enabled").checked=config.ocr.enabled;$("ocr-confidence").value=config.ocr.confidence;$("ocr-cpu-threads").value=config.ocr.cpu_threads;setError("ocr-error")}
function renderUpload(){const upload=config.upload,state=config.secret_status||{};$("upload-delete-after-success").checked=upload.delete_after_success;$("upload-connect-timeout").value=upload.connect_timeout;$("upload-read-timeout").value=upload.read_timeout;$("upload-total-timeout").value=upload.total_timeout;$("upload-max-retries").value=upload.max_retries;for(const id of["text-url","video-url"])$(id).value="";for(const id of["clear-text-url","clear-video-url"])$(id).checked=false;$("secret-state").textContent=`已配置：事件接口 ${state.text_url?"是":"否"}，视频接口 ${state.video_url?"是":"否"}`;setError("upload-error")}
function renderPreviews(){const cameras=(config?.cameras||[]).filter(item=>item.enabled!==false);$("camera-count").textContent=`${cameras.length} 路`;if(!cameras.some(item=>item.id===activeCameraId))activeCameraId=cameras[0]?.id||"";const active=cameras.find(item=>item.id===activeCameraId);$("previews").innerHTML=active?`<div class="preview-tabs">${cameras.map(item=>`<button class="${item.id===activeCameraId?"active":""}" data-camera="${escapeHtml(item.id)}">${escapeHtml(item.name||item.id)}</button>`).join("")}<button class="ghost" data-unbind="${escapeHtml(active.id)}">取消绑定</button></div><div class="preview"><img src="/api/preview/${encodeURIComponent(active.id)}" alt="${escapeHtml(active.name||active.id)}"><span>${escapeHtml(active.name||active.id)}</span></div>`:'<div class="empty">尚未添加摄像头</div>'}
function renderCameraSettings(){const cameras=config?.cameras||[];$("camera-settings").innerHTML=cameras.map(camera=>`<article class="device-editor" data-camera-id="${escapeHtml(camera.id)}"><div class="device-editor-title"><div><strong>${escapeHtml(camera.name||camera.id)}</strong><small>${escapeHtml(camera.id)}</small></div><label class="check-row"><input data-camera-field="enabled" type="checkbox" ${camera.enabled!==false?"checked":""}>启用</label></div><div class="form-grid"><label>摄像头 ID<input data-camera-field="id" value="${escapeHtml(camera.id)}" readonly></label><label>名称<input data-camera-field="name" value="${escapeHtml(camera.name||"")}" maxlength="80"></label><label>主码流 RTSP 地址<input data-camera-field="rtsp_url" value="${escapeHtml(camera.rtsp_url||"")}" required></label><label>实时转发目标（可选）<input data-camera-field="forward_url" value="${escapeHtml(camera.forward_url||"")}" placeholder="192.168.2.20:5000"></label></div><div class="actions"><button data-camera-save ${deviceBusy.has(camera.id)?"disabled":""}>保存此摄像头</button><button data-camera-delete class="danger" ${deviceBusy.has(camera.id)?"disabled":""}>删除摄像头</button></div><p class="form-error" aria-live="polite"></p></article>`).join("")||'<div class="empty">尚未绑定摄像头</div>';$("camera-add").disabled=cameras.length>=2}

const configRenderers={recording:renderRecording,ocr:renderOcr,upload:renderUpload,cameras:renderCameraSettings};
function renderConfig(value,sections=null){config=value;for(const section of sections||Object.keys(configRenderers))configRenderers[section]();if(!sections||sections.some(section=>["recording","cameras"].includes(section)))renderPreviews()}

function serialExtra(item){const values=[];if(item.last_heartbeat)values.push(`最近心跳 ${new Date(item.last_heartbeat).toLocaleString()}`);if(item.last_trigger)values.push(`最近触发 ${new Date(item.last_trigger).toLocaleString()}`);const accel=item.acceleration;if(accel&&[accel.x,accel.y,accel.z].every(Number.isFinite))values.push(`加速度 X ${accel.x}g · Y ${accel.y}g · Z ${accel.z}g`);return values.map(value=>`<br><span class="muted">${escapeHtml(value)}</span>`).join("")}
function renderStatus(status){const free=status.disk?.free,total=status.disk?.total;$("disk").textContent=`可用 ${formatBytes(free)} / ${formatBytes(total)}`;$("summary").textContent=status.accepting_events?`运行中 · 队列 拼接 ${status.queues.stitch} / OCR ${status.queues.ocr} / 上传 ${status.queues.upload}`:"磁盘空间不足，已暂停新事件";$("serials").innerHTML=Object.entries(status.serials||{}).map(([id,item])=>`<div class="status-card"><strong>${escapeHtml(id)}</strong><span class="${stateClass(item.state)}">${item.state==="bound"?"已绑定":item.state==="lost"?"连接已断开":"正在扫描"}</span><br><span>${item.port?`当前端口 ${escapeHtml(item.port)}`:`已检查 ${item.checked||0} 个端口`}</span>${serialExtra(item)}${item.error?`<br><span class="muted">${escapeHtml(item.error)}</span>`:""}</div>`).join("")||'<div class="empty">正在等待自动扫描</div>';$("recorders").innerHTML=Object.entries(status.recorders||{}).map(([id,item])=>`<div class="status-card"><strong>${escapeHtml(id)}</strong><span class="${stateClass(item.state)}">${escapeHtml(item.state)}</span><br><span>重连 ${item.restarts||0} 次</span>${item.error?`<br><span class="bad" title="${escapeHtml(item.error)}">${escapeHtml(item.error.slice(0,100))}</span>`:""}</div>`).join("")||'<div class="empty">没有运行中的录像器</div>';$("forwarders").innerHTML=Object.entries(status.forwarders||{}).map(([id,item])=>`<div class="status-card"><strong>${escapeHtml(id)}</strong><span class="${stateClass(item.state)}">${escapeHtml(item.state)}</span><br><span>${escapeHtml(item.target)} · 重连 ${item.restarts||0} 次</span>${item.error?`<br><span class="bad" title="${escapeHtml(item.error)}">${escapeHtml(item.error.slice(0,100))}</span>`:""}</div>`).join("")||'<div class="empty">尚未配置实时转发</div>';$("errors").innerHTML=(status.errors||[]).slice().reverse().map(item=>`<div>${escapeHtml(item.time)} · ${escapeHtml(item.message)}</div>`).join("")}
function renderEvents(items){$("events").innerHTML=items.map(item=>{const retry=!["waiting","pending"].includes(item.recording.status)&&!["waiting","pending"].includes(item.ocr.status)&&(item.text_upload.status!=="complete"||item.video_upload.status!=="complete");const processingFailed=item.recording.status==="failed"||item.ocr.status==="failed";return`<tr><td>${new Date(item.trigger_time*1000).toLocaleString()}<br><small>${escapeHtml(item.event_id)}</small></td><td>${escapeHtml(item.camera_id)}</td><td class="${stateClass(item.recording.status)}" title="${escapeHtml(item.recording.error||item.coverage.reason||"")}">${escapeHtml(item.recording.status)}</td><td class="${stateClass(item.ocr.status)}" title="${escapeHtml(item.ocr.error||"")}">${escapeHtml(item.ocr.status)} (${item.ocr.failed_frames||0}/${item.ocr.frames||0} 失败)</td><td>${(item.ocr.plates||[]).map(plate=>`${escapeHtml(plate.text)} ${(plate.confidence*100).toFixed(1)}%`).join("<br>")||"—"}</td><td class="${stateClass(item.text_upload.status)}" title="${escapeHtml(item.text_upload.error||"")}">${escapeHtml(item.text_upload.status)}</td><td class="${stateClass(item.video_upload.status)}" title="${escapeHtml(item.video_upload.error||"")}">${escapeHtml(item.video_upload.status)}</td><td>${retry?`<button data-retry="${escapeHtml(item.event_id)}|${escapeHtml(item.camera_id)}">重试上传</button>`:""}${processingFailed?`<br><small class="muted">处理阶段失败，无法在此重试</small>`:""}</td></tr>`}).join("")||'<tr><td colspan="8" class="empty">暂无事件</td></tr>'}
function deviceName(item){return[item.manufacturer,item.model].filter(Boolean).join(" ")||`摄像头 ${item.ip}`}
function bestStream(item){return(item.streams||[]).filter(stream=>stream.validated).sort((a,b)=>(b.width||0)*(b.height||0)-(a.width||0)*(a.height||0))[0]}

async function refresh(){try{const[status,events]=await Promise.all([api("/api/status"),api("/api/events")]);renderStatus(status);renderEvents(events)}catch(error){toast(error.message,true)}}
async function refreshLoop(){await refresh();setTimeout(refreshLoop,2000)}
function serializeConfigSave(action){const pending=configSave.then(action,action);configSave=pending.catch(()=>{});return pending}
async function persistConfig(value,button,section,message,extra={}){delete value.secret_status;button.disabled=true;try{const saved=await api("/api/config",{method:"PUT",body:JSON.stringify({config:value,...extra})});const restart=Boolean(saved.restart_required);delete saved.restart_required;renderConfig(saved,[section]);toast(restart?`${message}；监听地址将在重启后生效`:message);await refresh();return saved}finally{button.disabled=false}}
async function persistConfigChange(button,section,message,build){return serializeConfigSave(async()=>{const value=cloneConfig(),extra=build(value)||{};return persistConfig(value,button,section,message,extra)})}
async function saveGroup(buttonId,errorId,section,message,build){const button=$(buttonId);setError(errorId);try{await persistConfigChange(button,section,message,build)}catch(error){setError(errorId,error.message);toast(error.message,true)}}

async function bootstrap(){try{const data=await api("/api/bootstrap");csrf=data.csrf_token;renderConfig(data.config);renderStatus(data.status);autostartState=(await api("/api/autostart")).enabled;$("autostart").textContent=autostartState?"取消开机自启":"设置开机自启";await refresh();await pollScan();setTimeout(refreshLoop,2000)}catch(error){toast(error.message,true)}}

$("refresh").onclick=refresh;
$("trigger-event").onclick=async()=>{const button=$("trigger-event");button.disabled=true;try{const result=await api("/api/events/trigger",{method:"POST"});toast(`事件 ${result.event_id} 已触发`);await refresh()}catch(error){toast(error.message,true)}finally{button.disabled=false}};
$("save-recording").onclick=()=>saveGroup("save-recording","recording-error","recording","录像配置已保存并应用",value=>{value.recording.pre_seconds=numberValue("recording-pre-seconds","触发前录像时长",true);value.recording.post_seconds=numberValue("recording-post-seconds","触发后录像时长",true)});
$("save-ocr").onclick=()=>saveGroup("save-ocr","ocr-error","ocr","OCR 配置已保存并应用",value=>{value.ocr.enabled=$("ocr-enabled").checked;value.ocr.confidence=numberValue("ocr-confidence","OCR 最低置信度");value.ocr.cpu_threads=numberValue("ocr-cpu-threads","OCR CPU 线程数",true)});
$("save-upload").onclick=()=>saveGroup("save-upload","upload-error","upload","上传配置已保存并应用",value=>{value.upload.delete_after_success=$("upload-delete-after-success").checked;value.upload.connect_timeout=numberValue("upload-connect-timeout","连接超时");value.upload.read_timeout=numberValue("upload-read-timeout","读取超时");value.upload.total_timeout=numberValue("upload-total-timeout","总超时");value.upload.max_retries=numberValue("upload-max-retries","最大重试次数",true);return{secrets:{text_url:$("text-url").value.trim(),video_url:$("video-url").value.trim()},clear_secrets:[["clear-text-url","text_url"],["clear-video-url","video_url"]].filter(item=>$(item[0]).checked).map(item=>item[1])}});
async function removeCamera(cameraId,button,errorTarget=null){const camera=config.cameras.find(item=>item.id===cameraId),name=camera?.name||cameraId,expected=JSON.stringify(camera);if(!camera)return toast("摄像头配置已变化，请刷新页面",true);if(!confirm(`确定删除摄像头“${name}”？历史事件和录像不会删除。`))return;setError(errorTarget);setDeviceBusy(cameraId,true);button.closest("[data-camera-id]")?.querySelectorAll("button").forEach(item=>item.disabled=true);try{await serializeConfigSave(async()=>{const current=config.cameras.find(item=>item.id===cameraId);if(!current)throw new Error(`摄像头 ${cameraId} 已删除`);if(!sameDevice(current,expected))throw new Error(`摄像头 ${cameraId} 配置已变化，请重试`);const saved=await api(`/api/cameras/${encodeURIComponent(cameraId)}`,{method:"DELETE"});renderConfig(saved,["cameras"]);toast(`摄像头 ${name} 已删除`);await refresh()})}catch(error){deviceError(cameraId,errorTarget,error.message);toast(error.message,true)}finally{setDeviceBusy(cameraId,false);button.disabled=false}}
$("previews").onclick=async event=>{const unbind=event.target.closest("[data-unbind]");if(unbind){await removeCamera(unbind.dataset.unbind,unbind);return}const button=event.target.closest("[data-camera]");if(!button||button.dataset.camera===activeCameraId)return;activeCameraId=button.dataset.camera;renderPreviews()};
$("camera-settings").onclick=async event=>{const button=event.target.closest("button"),editor=button?.closest("[data-camera-id]");if(!button||!editor)return;const cameraId=editor.dataset.cameraId,camera=config.cameras.find(item=>item.id===cameraId),errorTarget=editor.querySelector(".form-error");if(!camera)return toast("摄像头配置已变化，请刷新页面",true);if(button.matches("[data-camera-delete]")){await removeCamera(cameraId,button,errorTarget);return}if(!button.matches("[data-camera-save]"))return;const expected=JSON.stringify(camera),fields={name:editor.querySelector('[data-camera-field="name"]').value.trim(),enabled:editor.querySelector('[data-camera-field="enabled"]').checked,rtsp_url:editor.querySelector('[data-camera-field="rtsp_url"]').value.trim(),forward_url:editor.querySelector('[data-camera-field="forward_url"]').value.trim()};setError(errorTarget);setDeviceBusy(cameraId,true);editor.querySelectorAll("button").forEach(item=>item.disabled=true);try{await persistConfigChange(button,"cameras",`摄像头 ${cameraId} 配置已保存`,value=>{const updated=value.cameras.find(item=>item.id===cameraId);if(!updated)throw new Error(`摄像头 ${cameraId} 已删除`);if(!sameDevice(updated,expected))throw new Error(`摄像头 ${cameraId} 配置已变化，请重试`);Object.assign(updated,fields);if(!updated.rtsp_url)throw new Error("主码流 RTSP 地址不能为空")})}catch(error){deviceError(cameraId,errorTarget,error.message);toast(error.message,true)}finally{setDeviceBusy(cameraId,false)}};

$("camera-add").onclick=async()=>{const button=$("camera-add");setError("camera-add-error");try{button.disabled=true;await serializeConfigSave(async()=>{if(config.cameras.length>=2)throw new Error("最多只能配置 2 路摄像头");const id=$("camera-id").value.trim();if(id)validateDeviceId(id,"摄像头 ID");const main=$("camera-main").value.trim();if(!main)throw new Error("主码流 RTSP 地址不能为空");const camera=await api("/api/cameras",{method:"POST",body:JSON.stringify({id,name:$("camera-name").value.trim(),rtsp_url:main,forward_url:$("camera-forward").value.trim()})});for(const field of["camera-id","camera-name","camera-main","camera-forward"])$(field).value="";renderConfig(await api("/api/config"),["cameras"]);toast(`摄像头 ${camera.id} 已添加`);await refresh()})}catch(error){setError("camera-add-error",error.message);toast(error.message,true)}finally{button.disabled=config?.cameras?.length>=2}};

$("scan-start").onclick=async()=>{try{await api("/api/scan",{method:"POST",body:JSON.stringify({subnet:$("subnet").value,port:$("onvif-port").value,username:$("onvif-user").value,password:$("onvif-pass").value})});$("onvif-pass").value="";toast("扫描已开始");pollScan()}catch(error){toast(error.message,true)}};
$("scan-cancel").onclick=async()=>{try{await api("/api/scan",{method:"DELETE"});toast("已请求取消扫描")}catch(error){toast(error.message,true)}};
async function pollScan(){clearTimeout(scanTimer);try{const data=await api("/api/scan");if(data.status==="idle")return;$("scan-progress").textContent=`${data.status} · ${data.completed}/${data.total} · 发现 ${data.found.length} · 失败 ${Object.keys(data.failures).length}`;$("scan-results").innerHTML=data.found.map((item,index)=>{const stream=bestStream(item),detail=stream?`主码流 ${stream.width||"?"}×${stream.height||"?"} · ${(stream.codec||"").toUpperCase()} · 已验证`:"没有验证通过的 RTSP 流";return`<div class="list-item"><div><strong>${escapeHtml(deviceName(item))}</strong><small>${escapeHtml(item.ip)} · ${escapeHtml(detail)}</small></div><button data-discovered="${index}" ${stream&&config.cameras.length<2?"":"disabled"}>添加此摄像头</button></div>`}).join("");$("scan-results").dataset.items=JSON.stringify(data.found);if(data.status==="running")scanTimer=setTimeout(pollScan,1000)}catch(error){toast(error.message,true)}}
$("scan-results").onclick=async event=>{const button=event.target.closest("[data-discovered]");if(!button)return;try{button.disabled=true;const items=JSON.parse($("scan-results").dataset.items||"[]"),item=items[Number(button.dataset.discovered)];if(!bestStream(item))throw new Error("设备没有验证通过的 RTSP 流");await serializeConfigSave(async()=>{if(config.cameras.length>=2)throw new Error("最多只能配置 2 路摄像头");const id=`cam_${item.ip.replaceAll(".","_")}`;await api("/api/cameras",{method:"POST",body:JSON.stringify({id,name:deviceName(item),scan_ip:item.ip,forward_url:$("scan-forward").value})});renderConfig(await api("/api/config"),["cameras"]);toast(`已添加 ${deviceName(item)}`);await refresh()})}catch(error){button.disabled=false;toast(error.message,true)}};
$("events").onclick=async event=>{const button=event.target.closest("[data-retry]");if(!button)return;const[eventId,cameraId]=button.dataset.retry.split("|");try{await api(`/api/events/${encodeURIComponent(eventId)}/${encodeURIComponent(cameraId)}/retry`,{method:"POST",body:"{}"});toast("上传任务已重新入队")}catch(error){toast(error.message,true)}};
$("autostart").onclick=async()=>{try{autostartState=!autostartState;await api("/api/autostart",{method:"PUT",body:JSON.stringify({enabled:autostartState})});$("autostart").textContent=autostartState?"取消开机自启":"设置开机自启";toast(autostartState?"已设置当前用户登录后自动运行":"已取消开机自启")}catch(error){autostartState=!autostartState;toast(error.message,true)}};
bootstrap();
